apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tt-rr-sstt-test
  janus-idp.io/tekton: tt-rr-sstt-test
  backstage.io/kubernetes-id: tt-rr-sstt-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tt-rr-sstt-test
resources:
- deployment.yaml
- route.yaml
- service.yaml
