apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tt-rr-sstt-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tt-rr-sstt-test 
  name: tt-rr-sstt-test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tt-rr-sstt-test 
